all: TokenInfo.class Tokenizer.class TokenizerMain.class
TokenInfo.class: TokenInfo.java
	    javac -d . -classpath . TokenInfo.java
Tokenizer.class: Tokenizer.java
	    javac -d . -classpath . Tokenizer.java
TokenizerMain.class: TokenizerMain.java
	    javac -d . -classpath . TokenizerMain.java
clean:
		rm -rf edu
